<?php

namespace Database\Seeders;

use App\Models\BuilderTemplate;
use Illuminate\Database\Seeder;

class BuilderTemplateSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->templates() as $template) {
            BuilderTemplate::query()->updateOrCreate(
                ['key' => $template['key']],
                $template
            );
        }
    }

    private function templates(): array
    {
        return [
            [
                'category' => 'sections',
                'key' => 'home_banner_carousel_section',
                'title' => 'Banner Carousel',
                'subtitle' => 'Home hero banner slider',
                'description' => 'Adds a visual banner carousel section with three starter banner cards. Best for Home, Watch, Inspire, or event promotion.',
                'badge' => 'Section Template',
                'glyph' => '▭',
                'tone' => 'cyan',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 10,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'home',
                    'sections' => [
                        [
                            'tab_key' => 'home',
                            'key' => 'template_home_banner_carousel',
                            'title' => 'Featured Banners',
                            'subtitle' => 'Main hero carousel for this app.',
                            'template' => 'banners',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'horizontal_scroll',
                                'layout_type' => 'horizontal_scroll',
                                'card_height' => 170,
                                'card_width' => 310,
                                'columns' => 1,
                                'source' => 'builder_template',
                                'preview_hint' => 'Horizontal banner carousel with large image cards.',
                            ],
                            'items' => [
                                [
                                    'type' => 'link',
                                    'title' => 'Welcome Banner',
                                    'subtitle' => 'Replace this with your main message.',
                                    'icon' => 'heroicon-o-photo',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => [
                                        'badge' => 'Featured',
                                        'action' => ['type' => 'route', 'route_key' => 'home'],
                                    ],
                                ],
                                [
                                    'type' => 'link',
                                    'title' => 'Featured Message',
                                    'subtitle' => 'Connect to a sermon, article, or watch page.',
                                    'icon' => 'heroicon-o-play',
                                    'sort_order' => 20,
                                    'is_enabled' => true,
                                    'payload_json' => [
                                        'badge' => 'Watch',
                                        'action' => ['type' => 'route', 'route_key' => 'watch'],
                                    ],
                                ],
                                [
                                    'type' => 'link',
                                    'title' => 'Special Notice',
                                    'subtitle' => 'Use this for events, announcements, or updates.',
                                    'icon' => 'heroicon-o-megaphone',
                                    'sort_order' => 30,
                                    'is_enabled' => true,
                                    'payload_json' => [
                                        'badge' => 'Notice',
                                        'action' => ['type' => 'route', 'route_key' => 'inspire'],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'horizontal_scroll',
                    'cards' => 3,
                    'what_it_creates' => ['1 banner section', '3 starter banner cards', 'Append-only safe records'],
                    'best_for' => ['Home', 'Watch', 'Inspire', 'Event announcements'],
                ],
            ],
            [
                'category' => 'sections',
                'key' => 'explore_tool_grid_section',
                'title' => 'Tool Grid',
                'subtitle' => 'Bible, Notes, Quote Creator, and Books',
                'description' => 'Adds a beginner-friendly app tools grid for Explore or Home.',
                'badge' => 'Section Template',
                'glyph' => '▦',
                'tone' => 'blue',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 20,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'explore',
                    'sections' => [
                        [
                            'tab_key' => 'explore',
                            'key' => 'template_explore_tool_grid',
                            'title' => 'Tools',
                            'subtitle' => 'Helpful app tools for users.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'grid',
                                'layout_type' => 'grid',
                                'columns' => 2,
                                'card_height' => 185,
                                'source' => 'builder_template',
                                'preview_hint' => 'Two-column grid for app tools.',
                            ],
                            'items' => [
                                [
                                    'type' => 'link',
                                    'title' => 'Quote Creator',
                                    'subtitle' => 'Create beautiful faith quote designs.',
                                    'icon' => 'quote_creator',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => ['engine' => 'quote_creator', 'action' => ['type' => 'engine', 'engine' => 'quote_creator']],
                                ],
                                [
                                    'type' => 'link',
                                    'title' => 'Notes',
                                    'subtitle' => 'Save personal study notes.',
                                    'icon' => 'notes',
                                    'sort_order' => 20,
                                    'is_enabled' => true,
                                    'payload_json' => ['engine' => 'notes', 'action' => ['type' => 'engine', 'engine' => 'notes']],
                                ],
                                [
                                    'type' => 'link',
                                    'title' => 'Bible',
                                    'subtitle' => 'Read and search scriptures.',
                                    'icon' => 'bible',
                                    'sort_order' => 30,
                                    'is_enabled' => true,
                                    'payload_json' => ['engine' => 'bible', 'action' => ['type' => 'engine', 'engine' => 'bible']],
                                ],
                                [
                                    'type' => 'link',
                                    'title' => 'Book Reader/Library',
                                    'subtitle' => 'Open books and reading resources.',
                                    'icon' => 'books',
                                    'sort_order' => 40,
                                    'is_enabled' => true,
                                    'payload_json' => ['engine' => 'books', 'action' => ['type' => 'engine', 'engine' => 'books']],
                                ],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'grid',
                    'cards' => 4,
                    'what_it_creates' => ['1 tools section', '4 tool cards', 'Engine-ready payloads'],
                    'best_for' => ['Explore', 'Home quick tools'],
                ],
            ],
            [
                'category' => 'sections',
                'key' => 'daily_scripture_section',
                'title' => 'Daily Scripture Block',
                'subtitle' => 'Daily verse card',
                'description' => 'Adds a daily scripture section that can later be edited from Daily Scripture.',
                'badge' => 'Widget',
                'glyph' => '✚',
                'tone' => 'cyan',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 30,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'home',
                    'sections' => [
                        [
                            'tab_key' => 'home',
                            'key' => 'template_home_daily_scripture',
                            'title' => 'Daily Scripture',
                            'subtitle' => 'Today’s scripture for users.',
                            'template' => 'scripture',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'scripture',
                                'layout_type' => 'scripture',
                                'card_height' => 210,
                                'source' => 'builder_template',
                                'preview_hint' => 'Single devotional scripture card.',
                            ],
                            'items' => [
                                [
                                    'type' => 'link',
                                    'title' => 'Daily Scripture',
                                    'subtitle' => 'Psalm 119:105',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => [
                                        'home_kind' => 'daily_scripture',
                                        'daily_kind' => 'daily_scripture',
                                        'scripture_reference' => 'Psalm 119:105',
                                        'scripture_text' => 'Thy word is a lamp unto my feet, and a light unto my path.',
                                        'scripture_note' => 'Edit this scripture from the Daily Scripture editor.',
                                        'ref' => 'Psalm 119:105',
                                        'verse' => 'Thy word is a lamp unto my feet, and a light unto my path.',
                                        'note' => 'Edit this scripture from the Daily Scripture editor.',
                                        'background_mode' => 'gradient',
                                        'bg_color' => '#160042',
                                        'bg_color_2' => '#0ea5e9',
                                        'text_color' => '#ffffff',
                                        'accent_color' => '#38bdf8',
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'scripture',
                    'cards' => 1,
                    'what_it_creates' => ['1 scripture section', '1 scripture card', 'Daily-card payload'],
                    'best_for' => ['Home', 'Inspire'],
                ],
            ],
            [
                'category' => 'pages',
                'key' => 'watch_page_live_and_playlist',
                'title' => 'Watch Page Layout',
                'subtitle' => 'Live stream and playlist blocks',
                'description' => 'Adds a Watch page structure with live stream and video playlist sections.',
                'badge' => 'Page Template',
                'glyph' => '▻',
                'tone' => 'purple',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 40,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'watch',
                    'sections' => [
                        [
                            'tab_key' => 'watch',
                            'key' => 'template_watch_live_stream',
                            'title' => 'Live Stream',
                            'subtitle' => 'Primary live broadcast section.',
                            'template' => 'video',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'video_feed',
                                'layout_type' => 'video_feed',
                                'card_height' => 210,
                                'source' => 'builder_template',
                                'preview_hint' => 'Main video/live stream block.',
                            ],
                            'items' => [
                                [
                                    'type' => 'web',
                                    'title' => 'Main Live Stream',
                                    'subtitle' => 'Replace URL with the correct live stream link.',
                                    'url' => '',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => ['action' => ['type' => 'live_stream']],
                                ],
                            ],
                        ],
                        [
                            'tab_key' => 'watch',
                            'key' => 'template_watch_video_playlist',
                            'title' => 'Video Playlist',
                            'subtitle' => 'Recent videos and playlists.',
                            'template' => 'video',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'horizontal_scroll',
                                'layout_type' => 'horizontal_scroll',
                                'card_height' => 170,
                                'card_width' => 290,
                                'source' => 'builder_template',
                                'preview_hint' => 'Horizontal video playlist strip.',
                            ],
                            'items' => [
                                [
                                    'type' => 'video',
                                    'title' => 'Playlist Card',
                                    'subtitle' => 'Connect this to YouTube playlist or video URL.',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => ['action' => ['type' => 'youtube_playlist']],
                                ],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'watch_page',
                    'cards' => 2,
                    'what_it_creates' => ['1 live section', '1 playlist section', '2 starter video records'],
                    'best_for' => ['Watch'],
                ],
            ],
            [
                'category' => 'cards',
                'key' => 'video_card_template',
                'title' => 'Video Card',
                'subtitle' => 'Thumbnail + play action',
                'description' => 'Starter video card payload for a section.',
                'badge' => 'Card Template',
                'glyph' => '▶',
                'tone' => 'purple',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 50,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'watch',
                    'sections' => [
                        [
                            'tab_key' => 'watch',
                            'key' => 'template_video_card_section',
                            'title' => 'Video Cards',
                            'subtitle' => 'A section containing one starter video card.',
                            'template' => 'video',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'horizontal_scroll',
                                'layout_type' => 'horizontal_scroll',
                                'source' => 'builder_template',
                                'preview_hint' => 'Single video-card starter section.',
                            ],
                            'items' => [
                                [
                                    'type' => 'video',
                                    'title' => 'New Video Card',
                                    'subtitle' => 'Edit this card and connect a video URL.',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => ['action' => ['type' => 'youtube_video']],
                                ],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'video_card',
                    'cards' => 1,
                    'what_it_creates' => ['1 section', '1 video card'],
                    'best_for' => ['Watch', 'Inspire'],
                ],
            ],
            [
                'category' => 'widgets',
                'key' => 'quick_launch_widget',
                'title' => 'Quick Launch Widget',
                'subtitle' => 'Shortcut row/grid',
                'description' => 'Adds a compact quick-launch block for important app destinations.',
                'badge' => 'Widget',
                'glyph' => '▦',
                'tone' => 'blue',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 60,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'home',
                    'sections' => [
                        [
                            'tab_key' => 'home',
                            'key' => 'template_quick_launch_widget',
                            'title' => 'Quick Launch',
                            'subtitle' => 'Fast access shortcuts.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'icon_grid',
                                'layout_type' => 'icon_grid',
                                'columns' => 4,
                                'source' => 'builder_template',
                                'preview_hint' => 'Compact icon launcher row or grid.',
                            ],
                            'items' => [
                                [
                                    'type' => 'link',
                                    'title' => 'Watch',
                                    'icon' => 'watch',
                                    'route' => 'watch',
                                    'sort_order' => 10,
                                    'is_enabled' => true,
                                    'payload_json' => ['action' => ['type' => 'route', 'route_key' => 'watch']],
                                ],
                                [
                                    'type' => 'link',
                                    'title' => 'Inspire',
                                    'icon' => 'inspire',
                                    'route' => 'inspire',
                                    'sort_order' => 20,
                                    'is_enabled' => true,
                                    'payload_json' => ['action' => ['type' => 'route', 'route_key' => 'inspire']],
                                ],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'quick_launch',
                    'cards' => 2,
                    'what_it_creates' => ['1 quick-launch section', '2 starter shortcut items'],
                    'best_for' => ['Home', 'More'],
                ],
            ],
            [
                'category' => 'forms',
                'key' => 'contact_form_placeholder_section',
                'title' => 'Contact Form',
                'subtitle' => 'Form-ready placeholder',
                'description' => 'Adds a placeholder contact form section. The real form engine can later bind to it.',
                'badge' => 'Form Template',
                'glyph' => '✉',
                'tone' => 'cyan',
                'status' => 'Planning',
                'apply_mode' => 'append',
                'sort_order' => 70,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'more',
                    'sections' => [
                        [
                            'tab_key' => 'more',
                            'key' => 'template_contact_form',
                            'title' => 'Contact Us',
                            'subtitle' => 'Send a message or request support.',
                            'template' => 'form',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'form',
                                'form_key' => 'contact',
                                'fields' => ['name', 'email', 'phone', 'message'],
                                'source' => 'builder_template',
                                'preview_hint' => 'Form placeholder block.',
                            ],
                            'items' => [],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'form',
                    'fields' => 4,
                    'what_it_creates' => ['1 form placeholder section', 'No items yet'],
                    'best_for' => ['More', 'Support'],
                ],
            ],
        ];
    }
}
