<?php

namespace Database\Seeders;

use App\Models\BuilderTemplate;
use Illuminate\Database\Seeder;

class BuilderTemplateExpansionSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->templates() as $template) {
            BuilderTemplate::query()->updateOrCreate(
                ['key' => $template['key']],
                $template
            );
        }
    }

    private function templates(): array
    {
        return [
            [
                'category' => 'sections',
                'key' => 'inspire_featured_articles_grid',
                'title' => 'Featured Articles Grid',
                'subtitle' => 'Inspire articles in a visual grid',
                'description' => 'Adds an Inspire section for featured articles, devotionals, motivation, or teaching highlights.',
                'badge' => 'Section Template',
                'glyph' => '▦',
                'tone' => 'blue',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 80,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'inspire',
                    'sections' => [
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_inspire_featured_articles',
                            'title' => 'Featured Articles',
                            'subtitle' => 'Selected teachings and inspiration.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'grid',
                                'layout_type' => 'grid',
                                'columns' => 2,
                                'card_height' => 190,
                                'source' => 'builder_template',
                            ],
                            'items' => [
                                ['type' => 'article', 'title' => 'Featured Teaching', 'subtitle' => 'Connect this card to an article.', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['action' => ['type' => 'route', 'route_key' => 'article_detail']]],
                                ['type' => 'article', 'title' => 'Motivation', 'subtitle' => 'Connect this card to a motivation post.', 'sort_order' => 20, 'is_enabled' => true, 'payload_json' => ['action' => ['type' => 'route', 'route_key' => 'motivation']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'grid',
                    'cards' => 2,
                    'what_it_creates' => ['1 article grid section', '2 starter article cards'],
                    'best_for' => ['Inspire', 'Articles', 'Motivation'],
                ],
            ],
            [
                'category' => 'sections',
                'key' => 'short_video_strip_section',
                'title' => 'Short Video Strip',
                'subtitle' => 'Short/reel style video section',
                'description' => 'Adds a horizontal short video section for Home or Inspire.',
                'badge' => 'Section Template',
                'glyph' => '▶',
                'tone' => 'purple',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 90,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'inspire',
                    'sections' => [
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_short_video_strip',
                            'title' => 'Short Videos',
                            'subtitle' => 'Quick inspiring videos.',
                            'template' => 'short_video_feed',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'horizontal_scroll',
                                'layout_type' => 'short_video_feed',
                                'card_height' => 220,
                                'card_width' => 150,
                                'source' => 'builder_template',
                            ],
                            'items' => [
                                ['type' => 'video', 'title' => 'Short Video 1', 'subtitle' => 'Connect a short video URL.', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['action' => ['type' => 'short_video']]],
                                ['type' => 'video', 'title' => 'Short Video 2', 'subtitle' => 'Connect a short video URL.', 'sort_order' => 20, 'is_enabled' => true, 'payload_json' => ['action' => ['type' => 'short_video']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'short_video_feed',
                    'cards' => 2,
                    'what_it_creates' => ['1 short video section', '2 starter short video cards'],
                    'best_for' => ['Home', 'Inspire', 'Short Videos'],
                ],
            ],
            [
                'category' => 'sections',
                'key' => 'books_library_shelf_section',
                'title' => 'Books Library Shelf',
                'subtitle' => 'Book reader/library visual shelf',
                'description' => 'Adds a book shelf section for library, devotional books, or reading resources.',
                'badge' => 'Section Template',
                'glyph' => '▤',
                'tone' => 'blue',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 100,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'explore',
                    'sections' => [
                        [
                            'tab_key' => 'explore',
                            'key' => 'template_books_library_shelf',
                            'title' => 'Books & Library',
                            'subtitle' => 'Reading resources and books.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'meta_json' => [
                                'layout_variant' => 'grid',
                                'layout_type' => 'grid',
                                'columns' => 2,
                                'card_height' => 190,
                                'source' => 'builder_template',
                            ],
                            'items' => [
                                ['type' => 'link', 'title' => 'Book Reader/Library', 'subtitle' => 'Open the app library.', 'icon' => 'books', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['engine' => 'books', 'action' => ['type' => 'engine', 'engine' => 'books']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'grid',
                    'cards' => 1,
                    'what_it_creates' => ['1 books section', '1 starter library card'],
                    'best_for' => ['Explore', 'Books', 'Library'],
                ],
            ],
            [
                'category' => 'pages',
                'key' => 'home_page_full_starter',
                'title' => 'Home Full Starter Page',
                'subtitle' => 'Banners, daily card, tools, and media shelf',
                'description' => 'Adds a complete Home page starter arrangement using multiple sections.',
                'badge' => 'Page Template',
                'glyph' => '⌂',
                'tone' => 'cyan',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 110,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'home',
                    'sections' => [
                        [
                            'tab_key' => 'home',
                            'key' => 'template_home_full_banners',
                            'title' => 'Home Banners',
                            'subtitle' => 'Main home page carousel.',
                            'template' => 'banners',
                            'is_enabled' => true,
                            'meta_json' => ['layout_variant' => 'horizontal_scroll', 'layout_type' => 'horizontal_scroll', 'card_height' => 170, 'card_width' => 310, 'source' => 'builder_template'],
                            'items' => [
                                ['type' => 'link', 'title' => 'Welcome Home', 'subtitle' => 'Edit this banner.', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['action' => ['type' => 'route', 'route_key' => 'home']]],
                            ],
                        ],
                        [
                            'tab_key' => 'home',
                            'key' => 'template_home_full_tools',
                            'title' => 'Quick Tools',
                            'subtitle' => 'Useful app shortcuts.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'meta_json' => ['layout_variant' => 'grid', 'layout_type' => 'grid', 'columns' => 2, 'source' => 'builder_template'],
                            'items' => [
                                ['type' => 'link', 'title' => 'Bible', 'icon' => 'bible', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['engine' => 'bible', 'action' => ['type' => 'engine', 'engine' => 'bible']]],
                                ['type' => 'link', 'title' => 'Notes', 'icon' => 'notes', 'sort_order' => 20, 'is_enabled' => true, 'payload_json' => ['engine' => 'notes', 'action' => ['type' => 'engine', 'engine' => 'notes']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'home_page',
                    'cards' => 3,
                    'what_it_creates' => ['2 home sections', '3 starter items'],
                    'best_for' => ['Home', 'New App Setup'],
                ],
            ],
            [
                'category' => 'cards',
                'key' => 'book_card_template',
                'title' => 'Book Card',
                'subtitle' => 'Book cover/card starter',
                'description' => 'Creates a starter book card inside a reusable book section.',
                'badge' => 'Card Template',
                'glyph' => '▤',
                'tone' => 'blue',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 120,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'explore',
                    'sections' => [
                        [
                            'tab_key' => 'explore',
                            'key' => 'template_book_card_section',
                            'title' => 'Book Cards',
                            'subtitle' => 'Starter section for book cards.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'meta_json' => ['layout_variant' => 'grid', 'layout_type' => 'grid', 'columns' => 2, 'source' => 'builder_template'],
                            'items' => [
                                ['type' => 'link', 'title' => 'New Book Card', 'subtitle' => 'Edit this book card.', 'icon' => 'books', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['engine' => 'books', 'action' => ['type' => 'engine', 'engine' => 'books']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'book_card',
                    'cards' => 1,
                    'what_it_creates' => ['1 section', '1 book card'],
                    'best_for' => ['Explore', 'Library'],
                ],
            ],
            [
                'category' => 'cards',
                'key' => 'quote_card_template',
                'title' => 'Quote Card',
                'subtitle' => 'Shareable quote card starter',
                'description' => 'Creates a starter quote card section with quote-ready payload.',
                'badge' => 'Card Template',
                'glyph' => '❝',
                'tone' => 'purple',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 130,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'inspire',
                    'sections' => [
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_quote_card_section',
                            'title' => 'Quotes',
                            'subtitle' => 'Inspirational quote cards.',
                            'template' => 'quote',
                            'is_enabled' => true,
                            'meta_json' => ['layout_variant' => 'quote', 'layout_type' => 'quote', 'source' => 'builder_template'],
                            'items' => [
                                ['type' => 'link', 'title' => 'Quote of the Day', 'subtitle' => 'Edit this quote card.', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['daily_kind' => 'daily_quote', 'quote' => 'Your quote goes here.', 'quote_source' => 'Source']],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'quote',
                    'cards' => 1,
                    'what_it_creates' => ['1 quote section', '1 quote card'],
                    'best_for' => ['Home', 'Inspire'],
                ],
            ],

            [
                'category' => 'tabs',
                'key' => 'inspire_tab_dynamic_starter_v2',
                'title' => 'Inspire Tab Dynamic Starter',
                'subtitle' => 'Featured, shorts, quotes, articles and insert blocks',
                'description' => 'Creates a scalable Inspire tab structure with featured articles, short video row, quote row, article list, and ad insert metadata. Safe append-only starter for Dunamis, Celebration, and future apps.',
                'badge' => 'Tab Template',
                'glyph' => '✦',
                'tone' => 'purple',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 10,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'inspire',
                    'sections' => [
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_inspire_featured_v2',
                            'title' => 'Featured Inspiration',
                            'subtitle' => 'Main featured teachings and highlights.',
                            'template' => 'featured_grid',
                            'is_enabled' => true,
                            'source_type' => 'content_channel',
                            'source_bucket' => 'motivation',
                            'layout_variant' => 'hero_compact',
                            'card_style' => 'image',
                            'size_preset' => 'featured',
                            'meta_json' => [
                                'layout_type' => 'hero_compact',
                                'layout_variant' => 'hero_compact',
                                'placement_type' => 'main_tab',
                                'source_type' => 'content_channel',
                                'source_bucket' => 'motivation',
                                'card_style' => 'image',
                                'size_preset' => 'featured',
                                'preview_hint' => 'Featured top cards for the Inspire tab.',
                            ],
                            'items' => [
                                ['type' => 'article', 'title' => 'Featured Teaching', 'subtitle' => 'Connect this to an article or teaching.', 'icon' => 'article', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['source_type' => 'content_channel', 'source_bucket' => 'motivation', 'action' => ['type' => 'route', 'route_key' => 'motivation']]],
                            ],
                        ],
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_inspire_short_video_insert_v2',
                            'title' => 'Inspire Shorts',
                            'subtitle' => 'Short videos inserted after featured content.',
                            'template' => 'short_video_feed',
                            'is_enabled' => true,
                            'source_type' => 'short_video_category',
                            'source_bucket' => 'short_videos',
                            'source_channel' => 'inspire',
                            'layout_variant' => 'short_video_feed',
                            'card_style' => 'video',
                            'size_preset' => 'poster',
                            'placement_type' => 'after_featured',
                            'meta_json' => [
                                'layout_type' => 'short_video_feed',
                                'layout_variant' => 'short_video_feed',
                                'placement_type' => 'after_featured',
                                'source_type' => 'short_video_category',
                                'source_bucket' => 'short_videos',
                                'source_channel' => 'inspire',
                                'card_width' => 150,
                                'card_height' => 220,
                                'card_style' => 'video',
                                'size_preset' => 'poster',
                                'preview_hint' => 'Backend-controlled short-video row.',
                            ],
                            'items' => [],
                        ],
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_inspire_quote_insert_v2',
                            'title' => 'Inspire Quotes',
                            'subtitle' => 'Dynamic quote row placed inside Inspire.',
                            'template' => 'quote',
                            'is_enabled' => true,
                            'source_type' => 'quote_channel',
                            'source_bucket' => 'quote_dr_eneches_quotes',
                            'layout_variant' => 'quote_carousel',
                            'card_style' => 'quote',
                            'size_preset' => 'poster',
                            'placement_type' => 'after_item_number',
                            'insert_after_items' => 3,
                            'meta_json' => [
                                'layout_type' => 'quote_carousel',
                                'layout_variant' => 'quote_carousel',
                                'placement_type' => 'after_item_number',
                                'insert_after_items' => 3,
                                'source_type' => 'quote_channel',
                                'source_bucket' => 'quote_dr_eneches_quotes',
                                'card_style' => 'quote',
                                'size_preset' => 'poster',
                                'preview_hint' => 'Quote row that can be reused for any quote bucket.',
                            ],
                            'items' => [],
                        ],
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_inspire_article_list_v2',
                            'title' => 'More Inspiration',
                            'subtitle' => 'Dynamic article list after insert blocks.',
                            'template' => 'article_list',
                            'is_enabled' => true,
                            'source_type' => 'content_channel',
                            'source_bucket' => 'motivation',
                            'layout_variant' => 'article_list',
                            'card_style' => 'image',
                            'placement_type' => 'main_tab',
                            'meta_json' => [
                                'layout_type' => 'article_list',
                                'layout_variant' => 'article_list',
                                'placement_type' => 'main_tab',
                                'source_type' => 'content_channel',
                                'source_bucket' => 'motivation',
                                'card_style' => 'image',
                                'preview_hint' => 'Normal article list following inserted blocks.',
                            ],
                            'items' => [],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'inspire_tab_v2',
                    'cards' => 4,
                    'what_it_creates' => ['Featured content section', 'Short video insert block', 'Quote insert block after item 3', 'Article list section'],
                    'best_for' => ['Inspire', 'Motivation', 'Message Highlights', 'Future church apps'],
                ],
            ],
            [
                'category' => 'items',
                'key' => 'icon_tool_item_template_v2',
                'title' => 'Icon Tool Item',
                'subtitle' => 'Reusable icon/card shortcut',
                'description' => 'Creates one beginner-friendly icon card inside the selected tab/section. Use it for Bible, Notes, Quote Creator, Books, Games, or any future engine.',
                'badge' => 'Item Template',
                'glyph' => '▣',
                'tone' => 'cyan',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 20,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'explore',
                    'sections' => [
                        [
                            'tab_key' => 'explore',
                            'key' => 'template_icon_tool_item_section',
                            'title' => 'Tool Shortcut',
                            'subtitle' => 'Starter section created for this icon item.',
                            'template' => 'grid',
                            'is_enabled' => true,
                            'layout_variant' => 'icon_grid',
                            'columns' => 2,
                            'meta_json' => ['layout_type' => 'icon_grid', 'layout_variant' => 'icon_grid', 'columns' => 2, 'placement_type' => 'main_tab', 'source_type' => 'manual_items', 'card_style' => 'icon'],
                            'items' => [
                                ['type' => 'link', 'title' => 'New Tool', 'subtitle' => 'Edit this card and connect an engine/action.', 'icon' => 'spark', 'item_kind' => 'tool_card', 'card_style' => 'icon', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['item_kind' => 'tool_card', 'card_style' => 'icon', 'engine' => 'custom', 'action' => ['type' => 'engine', 'engine' => 'custom']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'icon_item',
                    'cards' => 1,
                    'what_it_creates' => ['1 starter section', '1 icon/tool item'],
                    'best_for' => ['Explore', 'Home tools', 'More shortcuts'],
                ],
            ],
            [
                'category' => 'sections',
                'key' => 'native_ad_insert_block_v2',
                'title' => 'Native Ad Insert Block',
                'subtitle' => 'Backend-controlled ad placement block',
                'description' => 'Adds an ad slot metadata block that can be positioned after a chosen item number. This keeps ad placement backend-controlled and easy to disable later.',
                'badge' => 'Insert Block',
                'glyph' => 'AD',
                'tone' => 'blue',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 30,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'inspire',
                    'sections' => [
                        [
                            'tab_key' => 'inspire',
                            'key' => 'template_native_ad_insert_block',
                            'title' => 'Native Ad Slot',
                            'subtitle' => 'Inserted ad block after selected item count.',
                            'template' => 'ad_slot',
                            'is_enabled' => true,
                            'source_type' => 'ad_slot',
                            'layout_variant' => 'ad_block',
                            'placement_type' => 'after_item_number',
                            'insert_after_items' => 3,
                            'meta_json' => ['layout_type' => 'ad_block', 'layout_variant' => 'ad_block', 'placement_type' => 'after_item_number', 'insert_after_items' => 3, 'source_type' => 'ad_slot', 'ad_format' => 'native', 'preview_hint' => 'Native ad placeholder controlled from backend.'],
                            'items' => [],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'ad_block',
                    'cards' => 0,
                    'what_it_creates' => ['1 ad insert block section', 'Placement metadata after item 3'],
                    'best_for' => ['Inspire', 'Explore', 'Content lists'],
                ],
            ],
            [
                'category' => 'media',
                'key' => 'image_banner_media_block_v2',
                'title' => 'Image Banner Media Block',
                'subtitle' => 'Banner/card image starter',
                'description' => 'Creates a media-friendly banner/card block for event banners, campaign art, thumbnails, or app announcements.',
                'badge' => 'Media Template',
                'glyph' => '▭',
                'tone' => 'cyan',
                'status' => 'Ready',
                'apply_mode' => 'append',
                'sort_order' => 40,
                'is_active' => true,
                'payload_json' => [
                    'target_tab' => 'home',
                    'sections' => [
                        [
                            'tab_key' => 'home',
                            'key' => 'template_image_banner_media_block',
                            'title' => 'Image Banner',
                            'subtitle' => 'Upload or select an image from Media Library.',
                            'template' => 'banner_carousel',
                            'is_enabled' => true,
                            'layout_variant' => 'horizontal_scroll',
                            'card_style' => 'image',
                            'size_preset' => 'wide',
                            'meta_json' => ['layout_type' => 'horizontal_scroll', 'layout_variant' => 'horizontal_scroll', 'card_width' => 310, 'card_height' => 170, 'placement_type' => 'main_tab', 'source_type' => 'manual_items', 'card_style' => 'image', 'size_preset' => 'wide'],
                            'items' => [
                                ['type' => 'link', 'title' => 'New Banner', 'subtitle' => 'Edit image, title and action.', 'icon' => 'image', 'item_kind' => 'image_card', 'card_style' => 'image', 'sort_order' => 10, 'is_enabled' => true, 'payload_json' => ['item_kind' => 'image_card', 'card_style' => 'image', 'action' => ['type' => 'route', 'route_key' => 'home']]],
                            ],
                        ],
                    ],
                ],
                'preview_json' => [
                    'layout' => 'image_banner',
                    'cards' => 1,
                    'what_it_creates' => ['1 banner section', '1 image card'],
                    'best_for' => ['Home', 'Events', 'Announcements'],
                ],
            ],
        ];
    }
}
