<?php

use Illuminate\Database\Migrations\Migration;

return new class extends Migration
{
    /**
     * This migration was auto-generated by mistake after a proper
     * content_post_likes migration already existed.
     *
     * We keep this file as a no-op to avoid creating duplicate tables
     * or breaking migration history.
     */
    public function up(): void
    {
        // no-op
    }

    public function down(): void
    {
        // no-op
    }
};
